### ISSUE TITLE
postfix_sender_canonical_maps.db not updated

### ISSUE THREAD

**Issue by esprit-libre** [Oefenweb/ansible-postfix#111]
If run the playbook with this:
```yaml
postfix_sender_canonical_maps:
  - sender:                 "root"
    rewrite:                "root@email.com"
```
and then run it again with a change in `postfix_sender_canonical_maps`:
```yaml
postfix_sender_canonical_maps:
  - sender:                 "postmaster"
    rewrite:                "postmaster@email.com"
```
the `postmap` command is not launch again and and `/etc/postfix/postfix_sender_canonical_maps.db` not updated with new or modified entries.
In Postfix logs we can also see
```
warning: database /etc/postfix/sender_canonical_maps.db is older than source file /etc/postfix/sender_canonical_maps
```

**Comment by tersmitten** [comment]
Do you have an idea why?

**Comment by esprit-libre** [comment]
nope. I did not resolve this, I run manually `postmap` command :(

**Comment by ljurgs** [comment]
Are you able to run the playbook with the -vv verbosity level and inform if ansible reports a change on the `configure sender canonical maps` task? It should look like `changed: [hostname] => {"changed": true, ...}`. The handler won't run if a change isn't detected.

**Comment by esprit-libre** [comment]
Sorry for the delay.

I made some changes in my config to rewrite every sender:
```yaml
admin_mail: "original@email.com"
postfix_sender_canonical_maps:
  - sender:                 "/.+/"
    rewrite:                "{{ admin_mail }}"
postfix_sender_canonical_maps_database_type:    "regexp"
```

So, I ran twice:

1. No changes
```bash
TASK [oefenweb.postfix : configure sender canonical maps] *********************
task path: /home/user/Dev/gitlab.com/ansible/.roles_requirements/oefenweb.postfix/tasks/main.yml:127
Friday 17 September 2021  09:48:33 +0200 (0:00:00.029)       0:01:55.283 ****** 
ok: [edsdev] => (item={'sender': '/.+/', 'rewrite': 'original@email.com'}) => {"ansible_loop_var": "item", "backup": "", "changed": false, "item": {"rewrite": "original@email.com", "sender": "/.+/"}, "msg": ""}
```

2. With a change
```bash
TASK [oefenweb.postfix : configure sender canonical maps] *********************
task path: /home/user/Dev/gitlab.com/ansible/.roles_requirements/oefenweb.postfix/tasks/main.yml:127
Friday 17 September 2021  09:52:54 +0200 (0:00:00.026)       0:01:52.695 ****** 
changed: [edsdev] => (item={'sender': '/.+/', 'rewrite': 'changed@email.com'}) => {"ansible_loop_var": "item", "backup": "", "changed": true, "item": {"rewrite": "changed@email.com", "sender": "/.+/"}, "msg": "line replaced"}
NOTIFIED HANDLER oefenweb.postfix : postmap sender_canonical_maps for edsdev
```
