### ISSUE TITLE
smtp_tls_security_level should not be withing postfix_relaytls condition?

### ISSUE THREAD

**Issue by fliespl** [Oefenweb/ansible-postfix#127]
I have setup my postfix install with this flag set encrypt, yet receiving host seen this message as not encrypted.

I have noticed it was not added to config due to missing: postfix_relaytls (which I don't have setup).

Adding smtp_tls_security_level = encrypt manually & restarting service (without postfix_relaytls) fixed it.

Is it actually relay specific setting?

**Comment by tersmitten** [comment]
See #117

**Comment by tersmitten** [comment]
Make sure to have a look at #117 and #127

**Comment by fliespl** [comment]
I don't think that is true...

```
    - role: oefenweb.postfix
      postfix_raw_options:
        - 'smtp_tls_security_level = encrypt'
      become: true
```

Following setup works correctly with gmail (when not using relay).

And if I skip postfix_raw_options - it will fallback to unencrypted emails.
