### ISSUE TITLE
Old entries in recipient_canonical_maps/sender_canonical_maps/aliases are not cleaned up

### ISSUE THREAD

**Issue by adborden** [Oefenweb/ansible-postfix#87]
If I run the playbook with:
```yaml
recipient_canonical_maps:
  - recipient: root
  - rewrite: me@example.com
```

Then I run the playbook with:
```yaml
recipient_canonical_maps:
  - recipient: postmaster
  - rewrite: me@example.com
```

And then I inspect /etc/postfix/recipient_canonical_maps

```
$ cat /etc/postfix/recipient_canonical_maps
root me@example.com
postmaster me@example.com
```

**Comment by racke** [comment]
That's indeed a problem. Using the *lineinfile* module is not appropriate here. *copy* with content parameter or *template* would work better. Also both of these are more efficient for a larger number of entries in the list.

**Comment by racke** [comment]
For example:

```
- name: configure recipient canonical maps
  copy:
    dest: "{{ postfix_recipient_canonical_maps_file }}"
    content: |
      {% for item in postfix_recipient_canonical_maps %}
      {{ item.recipient }} {{ item.rewrite }}
      {% endfor %}
    owner: root
    group: root
    mode: 0644
```
Disadvantage: leaves an empty line in the file when the value is an empty array.
