### ISSUE TITLE
postmap should not be run when database type is regexp

### ISSUE THREAD

**Issue by adborden** [Oefenweb/ansible-postfix#89]
postmap fails with this error if you run it with the regexp hash type. It's not well documented, but it seems you [shouldn't run postmap when using the regexp database type](http://postfix.1071664.n5.nabble.com/first-timer-using-postmap-help-please-tp14908p14910.html).

```
postalias: fatal: unsupported dictionary type: regexp. Is the postfix-regexp package installed?
```

Running the role with this configuration:
```yaml
postfix_install:
  - postfix
  - postfix-pcre  # needed for regexp database type
  - mailutils
  - libsasl2-2
  - sasl2-bin
  - libsasl2-modules
postfix_default_database_type: regexp
postfix_recipient_canonical_maps:
  - recipient: /./
    rewrite: root
```

Ansible output:

```
RUNNING HANDLER [oefenweb.postfix : new aliases] *************************************************************************************************************
fatal: [catalog-harvester-next1tf.internal.sandbox.datagov.us]: FAILED! => {"changed": true, "cmd": ["newaliases"], "delta": "0:00:01.008573", "end": "2020-06-19 22:31:53.948906", "msg": "non-zero return code", "rc": 1, "start": "2020-06-19 22:31:52.940333", "stderr": "postalias: fatal: unsupported dictionary type: regexp. Is the postfix-regexp package installed?", "stderr_lines": ["postalias: fatal: unsupported dictionary type: regexp. Is the postfix-regexp package installed?"], "stdout": "", "stdout_lines": []}
```
