### ISSUE TITLE
no_log fails on Ansible 2.10

### ISSUE THREAD

**Issue by vladgh** [Oefenweb/ansible-postfix#98]
https://github.com/Oefenweb/ansible-postfix/blob/123eb6a1be24c31ad0f57cc7f532c2f8681b3c4d/tasks/main.yml#L70

The line above fails on Ansible 2.10.

A simple way to reproduce is with:

```YAML
- name: Debug
  hosts: all
  tasks:
    - debug:
        msg: "Check is {{ ansible_check_mode }}"
      no_log: not ansible_check_mode
```

```
TASK [d] *********************************************************************************
fatal: [vdev]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}
```

**Comment by tersmitten** [comment]
And how are we supposed to fix it (in a backward compatible way)?

**Comment by vladgh** [comment]
I just did some tests, and I think simply quoting the variable should fix it: 

```YAML
---
- name: Debug
  hosts: all
  tasks:
    - debug:
        msg: "Check is {{ ansible_check_mode }}"
      no_log: "{{ not ansible_check_mode }}"
```

<img width="808" alt="Screen Shot 2020-09-25 at 7 14 36 AM" src="https://user-images.githubusercontent.com/370069/94266004-145d5d00-feff-11ea-9d08-87ada6bc9dfe.png">
